AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB Tables for EKart Store'

Parameters:
  Environment:
    Type: String

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ekart-users-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ekart-products-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: product_id
          AttributeType: S
        - AttributeName: seller_id
          AttributeType: S
        - AttributeName: category
          AttributeType: S
      KeySchema:
        - AttributeName: product_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: seller-index
          KeySchema:
            - AttributeName: seller_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: category-index
          KeySchema:
            - AttributeName: category
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ekart-orders-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: order_id
          AttributeType: S
        - AttributeName: buyer_id
          AttributeType: S
        - AttributeName: seller_id
          AttributeType: S
      KeySchema:
        - AttributeName: order_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: buyer-index
          KeySchema:
            - AttributeName: buyer_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: seller-index
          KeySchema:
            - AttributeName: seller_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  CartsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ekart-carts-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH

  InventoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ekart-inventory-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: product_id
          AttributeType: S
      KeySchema:
        - AttributeName: product_id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  UsersTableName:
    Value: !Ref UsersTable
  ProductsTableName:
    Value: !Ref ProductsTable
  OrdersTableName:
    Value: !Ref OrdersTable
  CartsTableName:
    Value: !Ref CartsTable
  InventoryTableName:
    Value: !Ref InventoryTable
